### ISSUE TITLE
Netopeer-agents are not being stopped

### ISSUE THREAD

**Issue by krishnakumar4a4** [CESNET/netopeer#100]
Hi ,
we are using netopeer/libnetconf combination of 0.9 version.

We have a use case where a ssh connection is being made to the netopeer-server,some operations are perfomed and connection is closed.
This is a repetitive action which is sometimes leaving netopeer-agents which are not being killed when a ssh connection is closed.
As a result the netopeer-agent processes are being accumulated and reaching to a high value where no further connections are accepted(session closes when hello is given).

Could you please provide us a headstart to fix this issue. Is this an expected behavior for some reason,like pooling mechanism?

We are really in a critical situation to fix this problem asap.please help

Regards,
Krishna Kumar.

**Comment by rkrejci** [comment]
Hi, the main advice is probably to move to 0.10. There is no netopeer-agent since netopeer-server integrates SSH server.

Anyway, some hints you can try to check:
- what does it mean that "connection is closed"? Is the NETCONF's `<close-session>` performed correctly? Because in that case the agent should terminate correctly.
- even in case the SSH session is closed unexpectedly, the agent should terminate. It polls on the input file descriptor (pipe) from SSH daemon, so I would expect that POLLHUP or POLLERR would raise on the pipe - try to run the agent in debugger and examine what is happening there in more details

**Comment by krishnakumar4a4** [comment]
Hi,

Yes, <close-session> was perfect and leaves some netopeer-agents randomly. I can see the maximum netopeer-agent limit for 50 netopeer instances on a server is 140-150 and not accepting any more connections beyond that value.

As a quick work around,Wrote a shell script which constantly monitors the netopeer-agents. Once the netopeer-agent is dangling,its parent process id becomes 1. Hence it kills them by recognising them.

Thanks for information and help, I will also try to debug code as mentioned by you to find the root cause.
