### ISSUE TITLE
transAPI for RPC output node

### ISSUE THREAD

**Issue by rajeshPerumala** [CESNET/netopeer#120]
HI ,
    I'm new to netopeer and transAPI. I would like to know how to reply the output node of RPC. My RPC is
```
  rpc ping-test {
  	input {
        leaf destination-ip {
  			type inet:ip-address;
  		}
  	}
  	output {
  		leaf result {
  			type success-fail;
  		}
  	}
  }
```

**Comment by rkrejci** [comment]
Hi, in your RPC callback you are supposed to create the appropriate reply message. [The example](https://rawgit.com/CESNET/libnetconf/master/doc/doxygen/html/d9/d25/transapi.html#transapiTutorial-coding) shows how to return `<ok>`, but in the same way you can use other libnetconf functions (namely `nc_reply_data() or ncxml_reply_data()) to create the reply containing some data (as in case of e.g. `<get>` or `<get-config>` RPCs).

**Comment by rajeshPerumala** [comment]
HI Radek,
   Thank you for your answer. How <data> has to be in passed into the
nc_reply_data() function, can you please explain a  little more on this.

Regards,
rajesh

**Comment by rkrejci** [comment]
libnetconf has poor support for model-specific RPCs. So, in your case the `nc_reply_data()` will not work since there is no output `<data>` container (as e.g. in `<get>`). If you cannot change it in your data model, try to use [`nc_reply_build()`](https://rawgit.com/CESNET/libnetconf/master/doc/doxygen/html/d0/de2/group__reply.html#ga78b032942cee08721d51ea97acff68b5)
