### ISSUE TITLE
edit-config with configuration file doesn't work

### ISSUE THREAD

**Issue by sbenjara** [CESNET/netopeer#129]
[root@pq-pma-att-001 adtran]# netopeer-cli --help
netconf> ?
Netopeer CLI client, version 0.8.0
released as version 0.8.0
compile time: Aug 31 2016, 00:27:16

netconf> connect --login=netconf 10.2xx.2xx.1xx
The authenticity of the host '10.213.239.190' cannot be established.
Password: netconf

netconf> get-config --out config.xml running               --> generated conf file with running config.
netconf> edit-config --defop replace --config config.xml running   --> trying to apply the same config.
**edit-config: failed to parse the file.**
netconf> 

The same config works fine if i use the netconf editor (copy-paste) instead of input conf file.

**Comment by rkrejci** [comment]
That is because when stored into a file, the data are inserted into a `<config>` element to make the stored file valid XML document (with just a single top-level element). The NETCONF `:url` capability requires this format of the used files, so instead of sending data via NETCONF, you can make the file accessible for the server via the URL capability extension.

**Comment by sbenjara** [comment]
Hello Radek,
Thanks for your quick response. 

I've tried adding <config> element at the beginning and end of the config file. But this time i'm seeing different issue.

netconf>  edit-config --defop replace --config config.xml running  
Segmentation fault                         <-- netconf exiting with an exception
[root@pq-pma-att-001 adtran]#

**config:**
<config>
    <sysem xmlns="urn:ietf:params:xml:ns:yang:ietf-system"/><interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
    <interface>
      <name>lag 0/1</name>
      <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ieee8023adLag</type>
      <enabled>false</enabled>
    </interface>
    .......................
   <netconf xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
    <ssh>
      <listen>
        <interface>
          <address>0.0.0.0</address>
        </interface>
      </listen>
    </ssh>
  </netconf>
</config>

Could you please share the format of config file to be used in my case.

Thanks

**Comment by michalvasko** [comment]
Hi,
the segmentation fault should be fixed, but it won't really solve your problem. To use a config file in the CLI, it must have one of these 2 formats. Either it has a top-level element `<config>` in the namespace `urn:ietf:params:xml:ns:netconf:base:1.0` or it includes the data directly. You failed to load your data previously because you had several top-level elements, which technically is an invalid XML and hence the error you saw. In this case you must encapsulate the data in the `<config>` element, but do not forget the namespace (that caused the segmentation fault).

Regards,
Michal

**Comment by sbenjara** [comment]
Thanks Michal!!.
It worked after adding namespace attribute.

It will be good if we have the top level (<config>)tag added while pulling the config with "--out" option. I always use get-config and edit-config for backup/restore purpose. It will be very useful in such cases(without an extra effort).
