### ISSUE TITLE
Does netopeer 2 work on ARM v9?

### ISSUE THREAD

**Issue by sankettandulwadkar** [CESNET/netopeer#152]
Hi,

I was wondering if netopeer 2 works on ARM v9? I am planning to try and build it. If you have an guidelines for me, that would be great. 

Thanks!

--Sanket

**Comment by michalvasko** [comment]
Hi Sanket,
firstly, you created the issue in the old *netopeer*, while asking about the new *netopeer2*. But, to answer you, we do not work much with other architectures and the primary support is for **x64** (and have fixed some problems for **x86**, so that should work fine, too), which we develop on. If you want to develop on **arm v9**, you are on your own (but I think there may be some other people developing for this architecture, so you can try to ask for their support on *netopeer2* issue tracker). Still, you should not encounter compatibility issues because of a 32-bit architecture.

Regards,
Michal
