### ISSUE TITLE
ERROR: iface_get_ipv6_mtu: failed to read from "/proc/sys/net/...".

### ISSUE THREAD

**Issue by UnknowSelf** [CESNET/netopeer#156]
#./cfginterfaces-init datastore.xml 
ERROR: iface_get_ipv6_mtu: failed to read from "/proc/sys/net/...".
ERROR: iface_get_ipv6_mtu: failed to read from "/proc/sys/net/...".

My system is CentOS6.5. How can I resovle the provlem ?

**Comment by michalvasko** [comment]
Hi,
the small app tried to read MTU from your system from `/proc/sys/net/ipv6/conf/<interface-name>/mtu` for certain interface and failed to do so for some reason. You can check that the path exists for all your IPv6 interfaces and if it does not, it may be some invalid configuration of your system. Anyway, you are basically on your own since *netopeer* project was abandoned in favor of *netopeer2*.

Regards,
Michal
