### ISSUE TITLE
what version of netconf or/and of-config protocol dose netopeer-cli support?

### ISSUE THREAD

**Issue by herunkang2018** [CESNET/netopeer#167]
Hi ALL

I am confused with the netconf version that the lastest netopeer-cli implements.
When I installed of-config with ovs2.3.1 from [this ](https://github.com/openvswitch/of-config/blob/master/INSTALL.md)guide, I got this netconf client works fine with ofc-server, but when I tried another Java netconf client(from [this ](https://github.com/Juniper/netconf-java)repo), I got some errors from ofc-server's console log:

> ofc-server[94159]: Some ofc-agent connected to the UNIX socket.
> ofc-server[94159]: Unable to close session (not found)

but when netopeer-cli connects ofc-server, it outputs quite normally, like this:
connected:

> ofc-server[94159]: Some ofc-agent connected to the UNIX socket.
> ofc-server[94159]: Created dummy session 13 for user 'master' (UID 1000)
> ofc-server[94159]: New agent ID set to 14 (PID 32628, NCSID 13)

disconnect:

> ofc-server[94159]: Created dummy session 0 for user 'master' (UID 1000)
> ofc-server[94159]: Created dummy session 0 for user 'master' (UID 1000)
> ofc-server[94159]: Created dummy session 0 for user 'master' (UID 1000)
> ofc-server[94159]: Agent 14 removed.

By the way, what is the relationsip between OF-CONF version and NETCONF version?

Any reply is appreciated!

**Comment by michalvasko** [comment]
Hi,
if you notice, the guide is 3 years old which should be a hint not to use it. Anyhow, it seems to be working with *netopeer-cli* which is the most you can hope for after all that time. It is possible there is an issue with *netconf-java*, in which case we cannot do anything about it, or an issue with *of-config* or *netopeer-cli*, in which case there is nothing we will do because the software is old and the support for it is over.

Also, there is no relationship whatsoever between OF-CONF and NETCONF versions.

Regards,
Michal

**Comment by herunkang2018** [comment]
Hi @michalvasko ,
Sorry to reply back so lately and thanks for your detailed infomation.
Finally, I find some other netconf java libs like [JNC](https://github.com/tail-f-systems/JNC), can work well with ofc-server, like the netopeer does.

**Comment by vinayakpattar** [comment]
Hi @hackeryard ,
Please would you tell me which version of JNC you used, because I am not able to connect to device.
Thanks
Vinayak
