### ISSUE TITLE
Checking Subscription callback in Netopeer source 

### ISSUE THREAD

**Issue by vinayhb012114** [CESNET/netopeer#202]
hi @michalvasko,
I need to do certain action once subscription rpc triggered from netopeer-cli.
Our application needs some callback from netopeer-server to check this, once subscription triggered I need to do certain action from our application.
How to get any callback or any event kind of signal from netopeer source to application.

**Comment by michalvasko** [comment]
If you are talking about *netopeer2*, you can subscribe to the `/notifications:create-subscription` RPC and you will be notified **before** *netopeer2* actually creates the subscription. There is no other form of a notification. However, if you are really using *netopeer-server* then I cannot help you, it is completely obsolete.

**Comment by vinayhb012114** [comment]
Hi @michalvasko , I subscribed this "/notifications:create-subscription" from our application, even after triggering subscribe I did not get any call-back.
I am expecting call back from application whenever "subscribe" option is triggered from netopeer-cli.

**Comment by michalvasko** [comment]
I have just tested it and it works as it should but I probably should have mentioned one detail. You need to subscribe to the RPC with a priority other than `0` because *netopeer2* subscribes with that priority and there cannot be 2 subscriptions with the same priority. But like I said, are you using **netopeer2-server** or **netopeer-server**? If the latter then this will not work and you must update first.

**Comment by vinayhb012114** [comment]
@michalvasko
Thanks for the input. After setting priority other then 0, I am able to get callback.
