### ISSUE TITLE
Question: cfgsystem model init

### ISSUE THREAD

**Issue by JackLIN-F** [CESNET/netopeer#38]
Hi,
My netopeer-server is working. 
I don't know netopeer-server how to init cfgsystem model.
I have cfgsystem.so on /usr/local/lib/

Need I execute command: ./cfgsystem-init /usr/local/etc/netopeer//ietf-system/datastore.xml timezone-name authentication local-users??

Thanks

**Comment by michalvasko** [comment]
Hi,

that (or very similar one) is executed when you run make install on cfgsystem. You can execute it yourself, but usually there is no reason to. What exactly is your problem?

Regards,
Michal

**Comment by JackLIN-F** [comment]
Hi,
I need understand how to init for ietf-system module.
The event from libnetconf.  netopeer-server will call callback_n_netopeer_n_modules_n_module_n_enabled()

=====================================================
netopeer-server[3506]: Transapi calling callback /A:netopeer/A:modules/A:module/A:enabled with op ADD.
netopeer-server[3506]: Adding base model "/home/x86/netopeer-master/transAPI/cfgsystem/model/ietf-system.yin"
netopeer-server[3506]: ncds_new_internal: Relax NG validator set (/home/x86/netopeer-master/transAPI/cfgsystem/model/ietf-system-config.rng)
netopeer-server[3506]: ncds_new_internal: Schematron validator set (/home/x86/netopeer-master/transAPI/cfgsystem/model/ietf-system-schematron.xsl)

**Comment by JackLIN-F** [comment]
Hi,
How know to execute the callback function:callback_systemns_system_systemns_hostname on netopeer-server?  Where is stored the code?

Need to execute the cfgsystem-init  every reboot? or first time?

Thanks

**Comment by michalvasko** [comment]
Hi,

the callbacks are executed by libnetconf. Every time a change happens in the ietf-system model configuration, in the hostname leaf (added, deleted, modified), this specific callback is called (defined in cfgsystem.c). I have already explained to someone in the mailing list how the transAPI initialization works, so I'll just answer your question. You do not need to execute or do anything with cfgsystem-init binary, it's used only once during installation to make sure the startup configuration matches the actual system one (otherwise this transAPI module can seriously screw up your system during netopeer start).

Regards,
Michal

**Comment by JackLIN-F** [comment]
Hi Michal:
Thanks.

I change hostname on linux system. I get hostname from netopeer is no change.
After execute cfgsystem-init , I get new hostname.

Why?

**Comment by michalvasko** [comment]
Hi,
because Netopeer does not know that you manually changed your hostname (this can actually be handled, 8th point in the transAPI tutorial [1]), it expects all the changes to be made using it (monitoring external files goes a bit beyond that). Netopeer should be the device that applies the changes to the system, not the other way around. Only exception is the server start, only then it needs to know what your current configuration is, that's what transapi_init() does, scans your system for the current cofniguration (cfgsystem_init is just a wrapper for this function).

Regards,
Michal

[1] https://rawgit.com/CESNET/libnetconf/master/doc/doxygen/html/d9/d25/transapi.html#transapiTutorial

**Comment by JackLIN-F** [comment]
Hi Michal

Thanks
