### ISSUE TITLE
cfgsystem-init error

### ISSUE THREAD

**Issue by JackLIN-F** [CESNET/netopeer#39]
Hi,
The augeas_init() function on base\common.c
aug_match return -1 is error  => EXIT_FAILURE 
                   return !=0 is match cnt 
                   return 0 is no match  

So, if match >0, then return EXIT_FAILURE ??
Beasuse I execute cfgsystem-init. line139 on base\common.c return c=5

line139:
 	if ((c = aug_match(sysaugeas, "/augeas//error", &matches)) != 0) {
		aug_get(sysaugeas, matches[0], (const char**) msg);
		asprintf(msg, "Initiating augeas failed (%s: %s)", matches[0], *msg);
		augeas_close();
		for (i = 0; i < c; ++i) {
			free(matches[i]);
		}
		free(matches);
		return EXIT_FAILURE;
	}

=================================================

augeas 1.2.0 : augeas .c
int aug_match(const struct augeas *aug, const char *pathin, char ***matches) {
    struct pathx *p = NULL;
    struct tree *tree;
    int cnt = 0;

    api_entry(aug);

    if (matches != NULL)
        *matches = NULL;

    if (STREQ(pathin, "/")) {
        pathin = "/*";
    }

    p = pathx_aug_parse(aug, aug->origin, tree_root_ctx(aug), pathin, true);
    ERR_BAIL(aug);

    for (tree = pathx_first(p); tree != NULL; tree = pathx_next(p)) {
        if (! TREE_HIDDEN(tree))
            cnt += 1;
    }
    ERR_BAIL(aug);

    if (matches == NULL)
        goto done;

    if (ALLOC_N(*matches, cnt) < 0)
        goto error;

    int i = 0;
    for (tree = pathx_first(p); tree != NULL; tree = pathx_next(p)) {
        if (TREE_HIDDEN(tree))
            continue;
        (*matches)[i] = path_of_tree(tree);
        if ((*matches)[i] == NULL) {
            goto error;
        }
        i += 1;
    }
    ERR_BAIL(aug);
 done:
    free_pathx(p);
    api_exit(aug);
    return cnt;

 error:
    if (matches != NULL) {
        if (*matches != NULL) {
            for (i=0; i < cnt; i++)
                free((*matches)[i]);
            free(*matches);
        }
    }
    free_pathx(p);
    api_exit(aug);
    return -1;
}

**Comment by michalvasko** [comment]
Hi,

if you look at the string used in the aug_match() function, you will notice it is "/augeas//error", meaning it looks for errors and then, naturally, if it finds some, the overall result is an error. Please, open issues only if you have a specific example when you can say what in some exact use-case happens and what would you expect to happen. Otherwise you are just wasting our time, thank you.

Also, if it matches, the first error is printed, so you should know what to do to get rid of it.

Regards,
Michal
