### ISSUE TITLE
After disabling modules with netconf message, the information of supported modules via the <hello> message are not updated

### ISSUE THREAD

**Issue by classcwnd** [CESNET/netopeer#45]
When disable the module via netconf message, if the module includes other augment modules, the  information of supported augment modules via the <hello> message are not updated. 
Actually, the information of augment modules belong to the disabled module are still displayed in hello message.

**Comment by rkrejci** [comment]
The problem is that such an augment module can be used (augmenting or by import for get groupings) in other modules. So, this is how the Netopeer modules works right now and changing this with the current data models representation is to much demanding. Also the possibility of removing one of the server capability can be problematic for other sessions and it is not currently implemented as we would like to have it.

We want to target Netopeer modules mechanism in future with libyang data models, so improving this is in our TODO list, but there are many other things with higher priority.
