### ISSUE TITLE
TLS callhome on netopeer-server does not need libssh

### ISSUE THREAD

**Issue by wirelessr** [CESNET/netopeer#48]
Hi,

netopeer-server is a client of callhome, so it just use `nc_callhome_connect` of libnetconf. But the `configure` must ask for `nc_callhome_listen`. It takes a configure error when the libnetconf built **without libssh**. I think the `configure.in` should be modified and re-generate the `configure`.

**Comment by michalvasko** [comment]
Hi,

I looked through netopeer-server configures and even the source code and could not find any reference to nc_callhome_listen, it should work whether libnetconf supports it or not, since it uses it's own implementation of Call Home. Moreover, it does not even use nc_callhome_connect, so I must assume you're looking at some older version. Please use netopeer-server 0.8.0 and get back to us if you have more questions.

Regards,
Michal
