### ISSUE TITLE
File transfer between client and server

### ISSUE THREAD

**Issue by trangnambeo** [CESNET/netopeer#57]
Hi Radek,

In the current project, I'm trying to send a file from netopeer-cli to netopeer-server using scp (or any file transfer protocol). 
Could you tell me how to do that using libnetconf?

FYI, I could run the following example successfully:

\<rpc message-id="101"
          xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
       \<copy-config>
        < target>
         < url>file://checkpoint.conf< /url>
         < /target>
         < source>
          < running/>
         < /source>
       < /copy-config>
     < /rpc>

However, that example only shows me the ability of the netopeer-server to internally copy the running datastore to a specific file.
I would like to know a method that can transfer file from client to server.

Thanks,

**Comment by michalvasko** [comment]
Hi,

libnetconf is generally not meant to copy any files. The source and target in any RPC is supposed to be configuration (possibly in a file). So, copying a configuration file from a client to the server is possible (rather a side-effect than intentional) the way you described, just use an URL as a source, too. You can even specify *scp* as the transfer protocol, but you may encounter some authentication issues, which are out of the scope of NETCONF RFCs, therefore may not work perfectly and we will not spend time fixing it.

Regards,
Michal

**Comment by trangnambeo** [comment]
Thanks Michal.
